### ISSUE TITLE
undefined method `join' 

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_website#40]
Hi, 
I'm trying to get the supplejack_website up and running. I have connected it to my API, but when I try and execute a search I get repeated `undefined method join` errors. Here's the output:

![s 2017-01-31 at 11 00 50 am](https://cloud.githubusercontent.com/assets/444648/22480198/6ce5fbf0-e7a5-11e6-80ca-5c148b02971b.png)

at first I though this might be somekind of mismatch between my `record_schema.rb` and `supplejack_client.rb` contents but I have since adjusted them and I'm still seeing this error: 
![s 2017-01-31 at 11 04 31 am](https://cloud.githubusercontent.com/assets/444648/22480142/3785f294-e7a5-11e6-98c0-3ea15ba090c2.png)
![s 2017-01-31 at 11 04 53 am](https://cloud.githubusercontent.com/assets/444648/22480150/3b6409b4-e7a5-11e6-8e5d-934d2521bd0f.png)

and here's my parser
![s 2017-01-31 at 11 05 09 am](https://cloud.githubusercontent.com/assets/444648/22480152/3e2ccc62-e7a5-11e6-8722-fc7ad2e7522b.png)

any insights you could provide would be greatly appreciated:) 

Thanks, 

Dan

**Comment by EdwinRozario** [comment]
@telezoic In your Schema source_contributor_name is a defined as a String. You can use .join only for an Array. So it has to be a multivalue, which is an Array.

So your field should look like

> string :source_contributor_name, string  multi_value: true,    search_boost: 4, search_as: [:filter, :fulltext], namespace: :sj

in the Schema.

**Comment by telezoic** [comment]
Thanks @EdwinRozario! 
I can get results now, but it looks like I will need to need to further work to get to past the error page to see the detailed display for a retrieved item.   Maybe by including the Id field in my parser . . . 



`'0' is not a valid record id`

`def show`

    `@record = Record.find(params[:id], params[:search])`

D
